let columns = [];

/* =========================
   THEME
========================= */

const themeToggle =
  document.getElementById("themeToggle");

function updateThemeIcon(){
  const html = document.documentElement;
  const isDark =
    html.getAttribute("data-theme") === "dark";

  themeToggle.innerHTML = isDark
    ? `<i class="fa-solid fa-moon"></i>`
    : `<i class="fa-solid fa-sun"></i>`;
}

function loadTheme(){
  const savedTheme =
    localStorage.getItem("forge_theme");

  if(savedTheme){
    document.documentElement.setAttribute(
      "data-theme",
      savedTheme
    );
  }
  updateThemeIcon();
}

themeToggle.addEventListener("click", () => {
  const html = document.documentElement;
  const isDark =
    html.getAttribute("data-theme") === "dark";

  const newTheme =
    isDark ? "light" : "dark";

  html.setAttribute(
    "data-theme",
    newTheme
  );

  localStorage.setItem(
    "forge_theme",
    newTheme
  );

  updateThemeIcon();
});

/* =========================
   TAG SYSTEM
========================= */

const addBtn =
  document.getElementById("addColumnBtn");

const colInput =
  document.getElementById("colInput");

if (addBtn) addBtn.addEventListener("click", addColumn);

if (colInput) {
    colInput.addEventListener("keypress", function(e){
        if(e.key === "Enter"){
            e.preventDefault();
            addColumn();
        }
    });
}

function sanitizeColumn(value){
  return value
    .trim()
    .replace(/\s+/g, "_")
    .replace(/[^a-zA-Z0-9_]/g, "");
}

function addColumn(){
  const rawValue = colInput.value;
  const value = sanitizeColumn(rawValue);

  if(!value){
    showToast("Invalid column name");
    return;
  }

  const exists = columns.some(col =>
    col.toLowerCase() ===
    value.toLowerCase()
  );

  if(exists){
    showToast("Column already exists");
    return;
  }

  columns.push(value);
  colInput.value = "";
  renderTags();
  showToast("Column added");
}

function renderTags(){
  const container = document.getElementById("tagContainer");
  container.innerHTML = "";

  columns.forEach((column, index) => {
    const tag = document.createElement("div");
    tag.className = "tag";
    tag.innerHTML = `
      <span>${column}</span>
      <i class="fa-solid fa-xmark"></i>
    `;

    tag.querySelector("i")
      .addEventListener("click", () => {
        columns.splice(index, 1);
        renderTags();
        showToast("Column removed");
      });

    container.appendChild(tag);
  });
}

/* =========================
   GENERATOR (FIXED & IMPROVED)
========================= */

document
  .getElementById("generateBtn")
  .addEventListener("click", generateScript);

function generateScript(){
  const sheetInput = document.getElementById("sheetId").value.trim();
  const sheetName = document.getElementById("sheetName").value.trim();

  if(!sheetInput){
    log("Google Sheet ID is required", "error");
    return;
  }

  if(columns.length === 0){
    log("Add at least one column", "error");
    return;
  }

  const sheetId = extractSheetId(sheetInput);

  // Start Generating Script Content
  let code = `/**\n * Generated by ForgeAPI Studio\n * Target Sheet: ${sheetName}\n */\n\n`;
  code += `const SS_ID = "${sheetId}";\n`;
  code += `const SHEET_NAME = "${sheetName}";\n`;
  code += `const KEYS = ${JSON.stringify(columns)};\n\n`;

  // doPost Function
  code += `function doPost(e) {\n  const p = e.parameter;\n  const ss = SpreadsheetApp.openById(SS_ID).getSheetByName(SHEET_NAME);\n  try {\n`;
  
  if (document.getElementById('cInsert').checked) code += `    if (p.action === 'add') return addData(ss, p);\n`;
  if (document.getElementById('cUpdate').checked) code += `    if (p.action === 'update') return updateData(ss, p);\n`;
  if (document.getElementById('cDelete').checked) code += `    if (p.action === 'delete') return deleteData(ss, p);\n`;
  
  code += `    return res({error: "Action Invalid"});\n  } catch(e) { return res({error: e.toString()}); }\n}\n\n`;

  // doGet Function
  code += `function doGet(e) {\n  const ss = SpreadsheetApp.openById(SS_ID).getSheetByName(SHEET_NAME);\n`;
  if (document.getElementById('cRead').checked) {
      code += `  return getData(ss);\n`;
  } else {
      code += `  return res({error: "Read function is disabled"});\n`;
  }
  code += `}\n\n`;

  // CRUD Helpers
  code += `function addData(ss, p) {\n  const row = [new Date()];\n  KEYS.forEach(k => row.push(p[k] || ""));\n  ss.appendRow(row);\n  return res({status: "success"});\n}\n\n`;
  
  code += `function getData(ss) {\n  const data = ss.getDataRange().getValues();\n  const headers = data[0];\n  const rows = data.slice(1);\n  const result = rows.map(r => {\n    let obj = {};\n    headers.forEach((h, i) => obj[h] = r[i]);\n    return obj;\n  });\n  return res(result);\n}\n\n`;

  code += `function updateData(ss, p) {\n  const data = ss.getDataRange().getValues();\n  for (let i = 1; i < data.length; i++) {\n    if (data[i][0].toString() == p.id) {\n      KEYS.forEach((k, idx) => {\n        if (p[k]) ss.getRange(i + 1, idx + 2).setValue(p[k]);\n      });\n      return res({status: "updated"});\n    }\n  }\n  return res({error: "ID not found"});\n}\n\n`;

  code += `function deleteData(ss, p) {\n  const data = ss.getDataRange().getValues();\n  for (let i = 1; i < data.length; i++) {\n    if (data[i][0].toString() == p.id) {\n      ss.deleteRow(i + 1);\n      return res({status: "deleted"});\n    }\n  }\n  return res({error: "ID not found"});\n}\n\n`;

  code += `function res(obj) {\n  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);\n}`;

  // Finalize Output
  document.getElementById("codeOutput").value = code;

  log("Production script generated successfully", "success");
  showToast("Script generated");
}

/* =========================
   HELPERS
========================= */

function extractSheetId(input){
  if(input.includes("/d/")){
    return input.split("/d/")[1].split("/")[0];
  }
  return input;
}

/* =========================
   COPY
========================= */

document
  .getElementById("copyBtn")
  .addEventListener("click", copyCode);

function copyCode(){
  const code = document.getElementById("codeOutput");
  if(!code.value.trim()){
    showToast("Nothing to copy");
    return;
  }

  navigator.clipboard.writeText(code.value)
    .then(() => {
      showToast("Code copied successfully");
    })
    .catch(() => {
      showToast("Copy failed");
    });
}

/* =========================
   DOWNLOAD
========================= */

document
  .getElementById("downloadBtn")
  .addEventListener("click", downloadFile);

function downloadFile(){
  const code = document.getElementById("codeOutput").value;
  if(!code.trim()){
    showToast("Nothing to download");
    return;
  }

  const format = document.querySelector('input[name="format"]:checked').value;
  const blob = new Blob([code], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");

  a.href = url;
  a.download = `ForgeAPI.${format}`;
  document.body.appendChild(a);
  a.click();
  a.remove();

  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 1000);

  showToast("Download started");
}

/* =========================
   VALIDATE
========================= */

document
  .getElementById("validateBtn")
  .addEventListener("click", () => {
    if(columns.length === 0){
      log("No columns added", "error");
      return;
    }
    log("Validation successful", "success");
    showToast("Validation passed");
  });

/* =========================
   SIMULATE
========================= */

document
  .getElementById("simulateBtn")
  .addEventListener("click", () => {
    log("Simulation completed successfully", "success");
    showToast("Simulation completed");
  });

/* =========================
   LOG
========================= */

function log(message, type){
  const logBox = document.getElementById("logMessage");
  const color = type === "error" ? "var(--danger)" : "var(--success)";
  logBox.style.borderColor = color;
  logBox.innerHTML = `
    <i class="fa-solid fa-circle-info"></i>
    <span>${message}</span>
  `;
}

/* =========================
   TOAST
========================= */

let toastTimeout;
function showToast(message){
  const toast = document.getElementById("toast");
  clearTimeout(toastTimeout);
  toast.textContent = message;
  toast.classList.add("show");
  toastTimeout = setTimeout(() => {
    toast.classList.remove("show");
  }, 2200);
}

/* =========================
   INIT
========================= */

loadTheme();